# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order_queue_pb2 as order__queue__pb2


class OrderQueueStub(object):
    """The order queue service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/orderqueue.OrderQueue/Enqueue',
                request_serializer=order__queue__pb2.OrderRequest.SerializeToString,
                response_deserializer=order__queue__pb2.OrderResponse.FromString,
                )
        self.Dequeue = channel.unary_unary(
                '/orderqueue.OrderQueue/Dequeue',
                request_serializer=order__queue__pb2.DequeueRequest.SerializeToString,
                response_deserializer=order__queue__pb2.OrderRequest.FromString,
                )
        self.ElectLeader = channel.unary_unary(
                '/orderqueue.OrderQueue/ElectLeader',
                request_serializer=order__queue__pb2.ElectionRequest.SerializeToString,
                response_deserializer=order__queue__pb2.ElectionResponse.FromString,
                )
        self.ClearCurrentLeader = channel.unary_unary(
                '/orderqueue.OrderQueue/ClearCurrentLeader',
                request_serializer=order__queue__pb2.ClearLeaderRequest.SerializeToString,
                response_deserializer=order__queue__pb2.ClearLeaderResponse.FromString,
                )


class OrderQueueServicer(object):
    """The order queue service definition.
    """

    def Enqueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dequeue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ElectLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCurrentLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderQueueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=order__queue__pb2.OrderRequest.FromString,
                    response_serializer=order__queue__pb2.OrderResponse.SerializeToString,
            ),
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=order__queue__pb2.DequeueRequest.FromString,
                    response_serializer=order__queue__pb2.OrderRequest.SerializeToString,
            ),
            'ElectLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.ElectLeader,
                    request_deserializer=order__queue__pb2.ElectionRequest.FromString,
                    response_serializer=order__queue__pb2.ElectionResponse.SerializeToString,
            ),
            'ClearCurrentLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCurrentLeader,
                    request_deserializer=order__queue__pb2.ClearLeaderRequest.FromString,
                    response_serializer=order__queue__pb2.ClearLeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderqueue.OrderQueue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderQueue(object):
    """The order queue service definition.
    """

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderqueue.OrderQueue/Enqueue',
            order__queue__pb2.OrderRequest.SerializeToString,
            order__queue__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderqueue.OrderQueue/Dequeue',
            order__queue__pb2.DequeueRequest.SerializeToString,
            order__queue__pb2.OrderRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ElectLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderqueue.OrderQueue/ElectLeader',
            order__queue__pb2.ElectionRequest.SerializeToString,
            order__queue__pb2.ElectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearCurrentLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderqueue.OrderQueue/ClearCurrentLeader',
            order__queue__pb2.ClearLeaderRequest.SerializeToString,
            order__queue__pb2.ClearLeaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
